model:
  base_learning_rate: 1.0
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 250
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 64
    channels: 3
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss
    use_ema: False

    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [64]  # 1 epoch x 64 batches/epoch
        cycle_lengths: [2560] # Up to 40 more epochs
        f_start: [1.e-6]
        f_max: [5.e-5]
        f_min: [ 1.e-6]
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 1
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 6
        embed_dim: 512
        key: class_label

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.ct_rsna.CTSubset
      params:
        data_dir: "../data/ct-rsna/train/"
        labels_file: "train_set_dropped_nans.csv"
        size: 256
        flip_prob: 0.5
        subset_len: 1024
    validation:
      target: ldm.data.ct_rsna.CTSubset
      params:
        data_dir: "../data/ct-rsna/validation/"
        labels_file: "validation_set_dropped_nans.csv"
        size: 256
        flip_prob: 0
        subset_len: 128

lightning:
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      every_n_epochs: 5
      save_top_k: -1
      save_weights_only: true

  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 640  # Every 10 epochs
        log_on_batch_idx: false
        increase_log_steps: false
        max_images: 2